const type = 'POST',
    dataType = 'JSON',
    url = 'profileScript.php',
    calendarUrl = 'calendar/events.php',
    noText = '',
    loginText = 'Login',
    done = 'done',
    imageExtensions = ['jpg', 'png', 'jpeg', 'gif'],
    profileralreadyused = 'pralreadyused',
    profileAlreadyError = 'Profile Already Registered!',
    errorMsg = "An Error Occurred. Try Again!",
    updated = 'updated',
    success = 'success',
    submitText = 'SUBMIT',
    successfulText = 'SUCCESSFUL!',
    failedText2 = 'FAILED! Try Again',
    disabled = 'disabled',
    eyeOpened = '<i class="fas fa-eye-slash"></i>',
    eyeClosed = '<i class="fas fa-eye"></i>',
    at = '@',
    hash = '#',
    coma = ',',
    div = 'Div',
    dot = '.',
    yes = 'yes',
    no = 'no',
    txt = 'txt',
    elId = 'id',
    sid = 'sid',
    elTitle = 'title',
    elField = 'field',
    deptName = 'deptName',
    toggler = 'toggler',
    elMid = 'gid',
    elSid = 'sid',
    sidAttr = 'sid',
    src = 'src',
    elType = 'type',
    hType = 'element',
    textType = 'text',
    passwordType = 'password',
    numberType = 'number',
    selectType = 'select',
    button = 'buttopn',
    signupText = 'Sign Up',
    resetText = 'Reset Password',
    passwordRequired = 'Password Required',
    repeatPasswordText = 'Repeat Your Password',
    passwordNotMatch = 'Passwords Do Not Match',
    fNameRequired = 'First Name Required',
    lNameRequired = 'Last Name Required',
    pNumRequired = 'Mobile Number Required',
    pNumExists = 'Mobile Number Already In Use!',
    addressRequired = 'Address Required!',
    nrcRequired = 'NRC Required',
    postalcodeRequired = 'Postal Code Required',

    emailRequired = 'Email Required',
    signUpSuccessText = 'Signed Up Successfully!',
    signUpFailedText = 'Sign Up Failed. Network Issue!',
    signUpExistsText = 'exists',
    subscribeSuccessText = 'Subscription Successful.',
    subscribeFailedText = 'Failed To Subscribe.',
    subNumRequiredText = 'Subscriber Mobile Number Required',
    invalidMobileNumber = 'Invalid Mobile Number',
    amountRequiredText = 'Enter Amount',
    littleAmountText = 'Payment Starts From K25.00!',
    pleaseWait = 'Please Wait',
    failedText = 'Something Went Wrong, Try again.',
    failed = 'failed',
    wrongPasswordText = 'Wrong Password',
    wrongPasswordResponse = 'wrongpwd',
    emailNotExistsText = 'Email Not Recognized',
    emailExistsText = 'Email Already In Use!',
    emailNotExistsResponse = 'emnotexist',
    invalidEmailText = 'Invalid Email',
    nationalityRequiredText = 'Nationality Required',
    dobrequiredText = 'D.O.B Required',
    logoutNow = 'logoutNow',
    gettingSettingsText = 'Initializing';
var elementId = '',
    swotExpanded = false,
    formData = '';


const
    inputBorder = '.5px #273958 solid',
    redBorder = '.5px red solid',
    white = 'white',
    red = 'red',
    blue = '#002157',
    black = 'black',
    evtGray = '#CACFD2',
    transparent = 'transparent',
    px350 = '350px',
    px400 = '400px',
    px300 = '300px',
    px250 = '250px',
    px200 = '200px',
    px150 = '150px',
    gray = 'gray',
    pcpc200 = 'pc200%',
    pc100 = '100%',
    pc99 = '99%',
    pc98 = '98%',
    pc97 = '97%',
    pc96 = '96%',
    pc95 = '95%',
    pc94 = '94%',
    pc93 = '93%',
    pc92 = '92%',
    pc91 = '91%',
    pc90 = '90%',
    pc89 = '89%',
    pc88 = '88%',
    pc87 = '87%',
    pc86 = '86%',
    pc85 = '85%',
    pc84 = '84%',
    pc83 = '83%',
    pc82 = '82%',
    pc81 = '81%',
    pc80 = '80%',
    pc50 = '50%',
    pc45 = '45%',
    pc0 = '0%',

    px0 = '0px',
    px1 = '1px',
    px2 = '2px',
    px3 = '3px',
    px5 = '5px',
    px10 = '10px',
    px15 = '15px',
    px20 = '20px',
    px25 = '25px',
    px30 = '30px',
    px35 = '35px',
    px50 = '50px',
    px60 = '60px',
    pcneg100 = '-100%',
    flex = 'flex',
    block = 'block',
    inlineBlock = 'inline-block',
    none = 'none',
    auto = 'auto',
    scale0 = 'scale(0)',
    scale1 = 'scale(1)',
    scale1p5 = 'scale(1.5)',
    scale1p2 = 'scale(1.2)',
    scalep5 = 'scale(.5)',
    scalep6 = 'scale(.6)',
    scalep7 = 'scale(.7)',
    scalep8 = 'scaleX(.8)',
    scalep9 = 'scale(.9)',
    scale1p1 = 'scale(1.1)',
    translatex0 = 'translateX(0)',
    translatex200pc = 'translateX(200%)';


//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<CALENDAR VARIABLES>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
var evtDataShowing = false,
    currentShowingEvent = noText;
const
    evtMainBtn = $('.event-main-btn'),
    evtMainBtnIcon = $('.event-main-btn .btn-arrow'),
    evtData = $('.events-data'),
    evtDataInner = $('.calendar-sec .events-data .events-inner .events-data'),
    evtTitle = $('#etitle'),
    evtStartDate = $('#startdate'),
    evtEndDate = $('#enddate'),
    submitEventBtn = $('#addEventBtn'),
    evtBody = $('#evtBody'),
    deleteEvtBtn = $('.deleteEvent'),

    requiredFieldText = 'This Field Is Required!';

const
    loader = $('.loader'),
    loaderText = $('.loaderText'),
    dotHolder = $('.dotHolder');

//lessons
var lessonid = 4;
var allFilled = true;

// latest variables
const
    dn = 'd-n',
    df = 'd-f',
    ac = 'a-c',
    jc = 'j-c',
    fdcol = 'fd-col'